# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-02 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30, verbose_name='车辆信息')),
                ('picture', models.ImageField(default='normal.png', upload_to='', verbose_name='照片')),
                ('price', models.CharField(max_length=30, verbose_name='成交价格')),
                ('newprice', models.CharField(max_length=30, verbose_name='新车价格')),
                ('mileage', models.CharField(max_length=30, verbose_name='公里数')),
                ('orderNo', models.CharField(max_length=30, verbose_name='订单号')),
                ('orderStatus', models.IntegerField(blank=True, choices=[(1, '未出价'), (2, '已出价'), (3, '订单关闭')], default=1, verbose_name='订单状态')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('buy_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buser', to='userinfo.UserInfo', verbose_name='买家')),
                ('sale_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suser', to='userinfo.UserInfo', verbose_name='卖家')),
            ],
            options={
                'db_table': 'Orders',
                'verbose_name': '订单表',
                'verbose_name_plural': '订单表',
            },
        ),
    ]
